### ISSUE TITLE
Form prefixes

### ISSUE THREAD

**Issue by DirectDuck** [datalowe/django-formsets-tutorials#1]
Hello! Great article, but I want to point out that Django forms have a prefix parameter that allows multiple identical forms to be used without a formset. This solution certainly adds a lot of complexity, especially if the number of forms is changed using JavaScript, but in some situations it can be handy

But in any case, this is a pretty useful article, I will definitely wait for the second part

**Comment by datalowe** [comment]
Hi, thanks for the feedback :)

I updated the [first tutorial](https://datalowe.com/post/formsets-tutorial-1/) so that it now includes this:

> *Note: To be fair, if having different names for a set number of forms is the only thing you are worried about, there is an alternative solution, as raised by user DirectDuck in a [GitHub issue](https://github.com/datalowe/django-formsets-tutorials/issues/1). When instantiating forms you can [specify a 'prefix' parameter](https://docs.djangoproject.com/en/3.2/ref/forms/api/#django.forms.Form.prefix), which would solve the specific problem mentioned above. As we'll see however, formsets provide additional benefits.

 I had bits of the second tutorial lying around already and I had a bit of time this weekend, so I finally put it together and [uploaded it](https://datalowe.com/post/formsets-tutorial-2/). This second part was much more challenging to write since readers are bound to have very varying familiarity with JavaScript. It might have ended up too meandering and wordy. But if you have any thoughts about it, I'd be happy to hear them.

**Comment by DirectDuck** [comment]
Hi again!

The new article is really cool, and I'm glad to hear that there will be more articles on the formsets. JavaScript part was explained pretty well and I'm sure even a person with no prior JS knowledge will understand the flow.

At one time, when I needed to make formsets dynamic, I came across [this library](https://github.com/elo80ka/django-dynamic-formset). It has worked pretty well in production for me, and I think it would be nice to mention it as a ready-made solution.

**Comment by datalowe** [comment]
Thanks a lot! I'd seen the package mentioned but I didn't know how actively it's being used, so I wasn't sure whether to recommend it or not. I inserted this into [the second tutorial](https://datalowe.com/post/formsets-tutorial-2/), under 'About the code quality':

> If you want a more ready-made solution instead, or if you want to explore it after going through this tutorial, you might be interested in the [django-dynamic-formset](https://github.com/elo80ka/django-dynamic-formset) package. [Nicole Harris has written a tutorial about using formsets with it](https://whoisnicoleharris.com/2015/01/06/implementing-django-formsets.html), though the tutorial is quite old and might be partly outdated. I haven't read this particular post by Harris, but other material from her that I have read has been really good.

Hope you have a nice day :)
